// Generates the Content-Security-Policy and writes it into netlify.toml.
//
// Generated rather than hand-written because two of its directives depend on
// the build output: the inline <script> blocks are allowed by hash, and a hash
// changes whenever the block does. A hand-maintained CSP goes stale on the
// first edit to the theme-paint script, and a stale script hash does not
// degrade -- it blanks the page.
//
//   node tools/gen-csp.mjs          write it
//   node tools/gen-csp.mjs --check  fail if netlify.toml is out of date (CI)
//
// Two policies ship, because two kinds of thing live in dist/:
//
//   /*                 the 36 Astro pages, which after the handler conversion
//                      contain no executable inline script beyond the hashed
//                      theme-paint block
//   /wrc-tracker/*     two standalone apps carried over untouched, still full
//   /cmc-tracker/*     of inline handlers. They get their own relaxed policy
//                      rather than dragging 'unsafe-inline' onto the whole
//                      site, and rather than being rewritten -- they are
//                      explicitly out of scope for this work.
//
// style-src keeps 'unsafe-inline'. 153 inline style attributes remain, and
// removing them would be a large refactor for a much weaker vector than
// script injection. Saying so is more useful than a policy that looks strict
// and is not.

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const REPO = path.resolve(import.meta.dirname, '..');
const DIST = path.join(REPO, 'dist');
const TOML = path.join(REPO, 'netlify.toml');
const BEGIN = '# >>> generated by tools/gen-csp.mjs — do not edit by hand';
const END   = '# <<< end generated';

if (!fs.existsSync(DIST)) {
  console.error('dist/ not found — run `npm run build` first');
  process.exit(1);
}

/* ── collect the inline script hashes ─────────────────────────────────── */
const walk = d => fs.readdirSync(d, { withFileTypes: true }).flatMap(e => {
  const p = path.join(d, e.name);
  return e.isDirectory() ? walk(p) : p.endsWith('.html') ? [p] : [];
});

const pages = walk(DIST).filter(p => !p.includes('tracker'));
const hashes = new Set();
const RX = /<script(?![^>]*\bsrc=)([^>]*)>([\s\S]*?)<\/script>/g;

for (const p of pages) {
  const html = fs.readFileSync(p, 'utf8');
  for (const [, attrs, body] of html.matchAll(RX)) {
    // application/ld+json is data, not code: browsers never execute it and do
    // not check it against script-src. Hashing all 29 of them would add ~2KB
    // to every response for nothing. tests/csp-verify.mjs asserts that this is
    // actually true rather than trusting the reasoning.
    if (/ld\+json/.test(attrs)) continue;
    hashes.add(`'sha256-${crypto.createHash('sha256').update(body).digest('base64')}'`);
  }
}
const inline = [...hashes].sort();

/* ── the policy ───────────────────────────────────────────────────────── */
const site = [
  `default-src 'self'`,
  `base-uri 'self'`,
  `object-src 'none'`,
  `frame-ancestors 'self'`,
  `form-action 'self'`,
  // GA is injected as a <script src> at runtime by config.js when an id is set.
  `script-src 'self' ${inline.join(' ')} https://www.googletagmanager.com`,
  `style-src 'self' 'unsafe-inline' https://fonts.googleapis.com`,
  `font-src 'self' https://fonts.gstatic.com`,
  `img-src 'self' data: https://images.unsplash.com https://img.youtube.com https://i.ytimg.com https://www.googletagmanager.com`,
  `connect-src 'self' https://fpzgcijbryvddtpegcmm.supabase.co https://www.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com`,
  `frame-src https://www.youtube.com https://www.youtube-nocookie.com`,
  `upgrade-insecure-requests`,
].join('; ');

// The trackers are untouched legacy: inline handlers throughout, plus a CDN
// script and their own Supabase project. Their origins are read out of the
// built files rather than written here, because a policy that guesses at what
// a frozen app needs is how you find out in production that its Excel export
// is broken. Widening automatically is the right trade for code that is
// explicitly out of scope: breaking it is the larger risk, and it is already
// isolated to its own two paths.
const trackerOrigins = new Set();
for (const t of ['wrc-tracker', 'cmc-tracker']) {
  const f = path.join(DIST, t, 'index.html');
  if (!fs.existsSync(f)) continue;
  for (const m of fs.readFileSync(f, 'utf8').matchAll(/https:\/\/[a-zA-Z0-9.-]+/g)) {
    trackerOrigins.add(m[0]);
  }
}
const tOrigins = [...trackerOrigins].sort().join(' ');

const tracker = [
  `default-src 'self'`,
  `base-uri 'self'`,
  `object-src 'none'`,
  `frame-ancestors 'self'`,
  `form-action 'self'`,
  `script-src 'self' 'unsafe-inline' ${tOrigins}`,
  `style-src 'self' 'unsafe-inline' https://fonts.googleapis.com`,
  `font-src 'self' https://fonts.gstatic.com`,
  `img-src 'self' data: https:`,
  `connect-src 'self' ${tOrigins}`,
].join('; ');

const block = `${BEGIN}
# ${inline.length} inline script hash(es); regenerate after any build that
# changes an inline <script>. \`node tools/gen-csp.mjs --check\` fails if stale.

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "${site}"

[[headers]]
  for = "/wrc-tracker/*"
  [headers.values]
    Content-Security-Policy = "${tracker}"

[[headers]]
  for = "/cmc-tracker/*"
  [headers.values]
    Content-Security-Policy = "${tracker}"

# The student portal reaches the application by a token in the URL. Without
# this, following any outbound link from that page hands the token to the other
# site in the Referer header, and a token in someone's analytics is a token
# they have.
[[headers]]
  for = "/portal/*"
  [headers.values]
    Referrer-Policy = "no-referrer"
    X-Robots-Tag = "noindex, nofollow"

# The console has no token in its URL, so the default Referrer-Policy is fine.
# It is still not public content.
[[headers]]
  for = "/staff/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
${END}`;

const toml = fs.readFileSync(TOML, 'utf8');
const has = toml.includes(BEGIN);
const next = has
  ? toml.replace(new RegExp(`${BEGIN}[\\s\\S]*?${END}`), block)
  : toml.trimEnd() + '\n\n' + block + '\n';

if (process.argv.includes('--check')) {
  if (next !== toml) {
    console.error('netlify.toml CSP is out of date — run: node tools/gen-csp.mjs');
    process.exit(1);
  }
  console.log('netlify.toml CSP is current');
} else {
  fs.writeFileSync(TOML, next);
  console.log(`wrote CSP with ${inline.length} inline hash(es)`);
}

export { site, tracker };
